# Generated by Django 5.1.1 on 2024-09-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_at_alter_project_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
